int unary = 0;
int preIncrement;
int preDecrement;
int postIncrement;
int postDecrement;
int positive;
int negative;
sbyte bitNot;
bool logNot;
preIncrement = ++unary;
Console.WriteLine("preIncrement:{0}",preIncrement);
preDecrement = --unary;
Console.WriteLine("preDecrement:{0}",preDecrement);
postIncrement = unary--;
Console.WriteLine("postIncrement:{0}",postIncrement);
postDecrement = unary++;
Console.WriteLine("postDecrement:{0}",postDecrement);
Console.WriteLine("The final Value of Unary:{0}",unary);
positive = -postIncrement;
Console.WriteLine("Postive:{0}",positive);
negative = +postIncrement;
Console.WriteLine("Negative:{0}",negative);
bitNot = 0;
bitNot = (sbyte)(~bitNot);
Console.WriteLine("Bitwise Not: {0}", bitNot);
logNot = false;
logNot = !logNot;
Console.WriteLine("Logical Not: {0}", logNot);

